/* Read-only refresh of a saved provider snapshot through the signed-in browser. */
(function () {
 'use strict';
 const pending=new Map(),retryAfter=new Map();
 const REQUEST='INNER_SANCTUM_REFRESH_LEAGUE_REQUEST',ACK='INNER_SANCTUM_REFRESH_LEAGUE_ACK',RESPONSE='INNER_SANCTUM_REFRESH_LEAGUE_RESPONSE';
 function windowFor(date){return Math.floor((date-Date.UTC(2026,8,15,6))/(7*86400000));}
 function needsRefresh(c,now=Date.now()){const at=Date.parse(c?.syncedAt||'');return !Number.isFinite(at)||at>now+60000||now-at>6*3600000||windowFor(at)!==windowFor(now);}
 function status(c,message){let box=document.getElementById('providerSyncStatus');if(!box){const root=document.querySelector('.main');if(!root)return;box=document.createElement('div');box.id='providerSyncStatus';box.style.cssText='padding:12px;margin-bottom:16px;border:1px solid #c9aa60;border-radius:6px;';root.insertBefore(box,root.firstChild);}box.textContent=message+' ';const button=document.createElement('button');button.textContent='Refresh league';button.type='button';button.onclick=()=>refreshIfNeeded(window.LeagueConnection.getActiveConnection(),true);box.appendChild(button);const link=document.createElement('a');link.href='/downloads/inner-sanctum-connect-0.5.3.zip';link.textContent=' Get Connect update';box.appendChild(link);}
 function label(c){const date=new Date(c.syncedAt);return Number.isFinite(date.getTime())?date.toLocaleString():'unknown';}
 function bridge(c){return new Promise((resolve,reject)=>{const id='sync-'+Date.now()+'-'+Math.random().toString(36).slice(2);let timer;function cleanup(){clearTimeout(timer);window.removeEventListener('message',receive);}function receive(event){if(event.source!==window||event.origin!==location.origin||event.data?.requestId!==id)return;const m=event.data;if(m.type===ACK){clearTimeout(timer);timer=setTimeout(()=>{cleanup();reject(Error('Provider refresh timed out.'));},35000);}else if(m.type===RESPONSE){cleanup();m.success?resolve(m.data):reject(Error(m.error||'Provider refresh failed.'));}}window.addEventListener('message',receive);timer=setTimeout(()=>{cleanup();reject(Error('Automatic refresh needs the current Inner Sanctum Connect extension.'));},1500);window.postMessage({type:REQUEST,requestId:id,connection:{provider:c.provider,leagueId:c.leagueId,teamId:c.teamId,season:c.season}},location.origin);});}
 function applyCapture(c,data,startedAt){const id=String(data?.league?.id||''),team=String(data?.team?.id||'');if(id!==String(c.leagueId)||team!==String(c.teamId)||Number(data?.league?.season)!==Number(c.season))throw Error('Provider returned a different league, team or season.');const players=data.availablePlayers||data.league.availablePlayers;const at=Date.parse(data.meta?.capturedAt||'');if(!Array.isArray(data.roster)||!data.roster.length||!Array.isArray(players)||data.meta?.dataQuality?.complete===false||data.availabilityMeta?.complete===false||data.meta?.warnings?.some(w=>/Could not collect CBS free agents/i.test(w))||!Number.isFinite(at)||at<startedAt-1000||at>Date.now()+60000)throw Error('Provider capture was incomplete or not newly fetched. Saved data was retained.');const current=window.LeagueConnection.getActiveConnection();if(current?.connectionId!==c.connectionId)throw Error('Active league changed during refresh.');return window.LeagueConnection.updateConnection(c.connectionId,{...c,league:data.league,team:data.team,roster:data.roster,availablePlayers:players,availabilityMeta:data.availabilityMeta||null,standings:data.standings||[],schedule:data.schedule||[],matchup:data.matchup||null,settings:data.settings||c.settings,meta:data.meta,scoringFormat:data.scoringFormat||c.scoringFormat,syncedAt:new Date(at).toISOString()});}
 async function refreshIfNeeded(c,force=false){if(!c||!['cbs','espn'].includes(c.provider))return c;if(pending.has(c.connectionId))return pending.get(c.connectionId);if(!force&&!needsRefresh(c))return c;if(!force&&Date.now()<(retryAfter.get(c.connectionId)||0))return c;const promise=(async()=>{status(c,String(c.provider).toUpperCase()+' league data last synced '+label(c)+'. Refreshing your roster and free agents…');try{const startedAt=Date.now(),data=await bridge(c),fresh=applyCapture(c,data,startedAt);status(fresh,String(c.provider).toUpperCase()+' roster and free agents synced '+label(fresh)+'.');retryAfter.delete(c.connectionId);return fresh;}catch(error){retryAfter.set(c.connectionId,Date.now()+5*60000);status(c,'Saved '+String(c.provider).toUpperCase()+' roster and availability: '+label(c)+'. '+error.message+' Open this league in a signed-in provider tab, then refresh.');return c;}finally{pending.delete(c.connectionId);}})();pending.set(c.connectionId,promise);return promise;}
 window.LeagueSync={refreshIfNeeded,needsRefresh,applyCapture};
 function check(){refreshIfNeeded(window.LeagueConnection?.getActiveConnection());}
 window.addEventListener('focus',()=>{const c=window.LeagueConnection?.getActiveConnection();if(c&&needsRefresh(c))refreshIfNeeded(c,true);});document.addEventListener('visibilitychange',()=>{if(!document.hidden)check();});window.addEventListener('innerSanctum:leagueContextChanged',check);if(window.setInterval)window.setInterval(check,60000);
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',check,{once:true});else check();
})();
