[build]
  publish = "."
  functions = "netlify/functions"

[context.production]
  environment = { SECRETS_SCAN_ENABLED = "false" }

[[redirects]]
  from = "/landing"
  to = "/theinnersanctum.xyz/landing.html"
  status = 200
