'use strict';
const assert=require('assert');
const {criticalCheckpoint,dailyRuns}=require('../netlify/functions/_availability-refresh-rhythm');
const {completeCache,nextJob,inspectJobs}=require('../netlify/functions/_weekly-refresh-recovery');
const {reserveTank01Calls}=require('../netlify/functions/_tank01-daily-budget');
const ms=s=>Date.parse(s);
const schedule={season:2026,week:5,games:[{gameDate:'20261008',gameTime:'8:15p'}]};
assert.strictEqual(criticalCheckpoint(schedule,ms('2026-10-08T22:59:00Z'))?.reason,'after-practice');
assert.strictEqual(criticalCheckpoint(schedule,ms('2026-10-08T23:00:00Z')).reason,'pregame-75');
assert.strictEqual(criticalCheckpoint(schedule,ms('2026-10-08T23:55:00Z')).reason,'pregame-20');
assert.strictEqual(criticalCheckpoint(schedule,ms('2026-10-09T00:15:00Z')),null,'never refresh a started game as pregame');
const winter={games:[{gameDate:'20261102',gameTime:'8:15p'}]};
assert.strictEqual(criticalCheckpoint(winter,ms('2026-11-03T00:00:00Z')).reason,'pregame-75','kickoff respects Eastern DST');
const overseas={games:[{gameDate:'20261011',gameTime:'9:30a'}]};
assert.strictEqual(criticalCheckpoint(overseas,ms('2026-10-11T12:15:00Z')).reason,'pregame-75','international morning game');
assert.strictEqual(criticalCheckpoint({games:[{gameStatus:'postponed',gameTime_epoch:ms('2026-10-08T23:30:00Z')/1000}]},ms('2026-10-08T23:00:00Z')),null);
assert.strictEqual(criticalCheckpoint(null,ms('2026-11-05T23:10:00Z')).reason,'after-practice','practice clock respects DST');
assert.strictEqual(criticalCheckpoint(null,ms('2026-10-07T22:10:59Z')).at,ms('2026-10-07T22:00:00Z'),'checkpoint stable across seconds');
assert.strictEqual(dailyRuns(ms('2026-10-11T12:00:00Z')),10);assert.strictEqual(dailyRuns(ms('2026-10-13T00:00:00Z')),4);
const now=ms('2026-10-08T23:05:00Z'),checkpoint=criticalCheckpoint(schedule,now);
const cache={updatedAt:'2026-10-08T22:00:00Z',teamsSucceeded:32,teamsFailed:0,players:Object.fromEntries(Array.from({length:1000},(_,i)=>[i,{}]))};
const job={store:'player-data',criticalCheckpoint:checkpoint,criticalDue:true};
assert.strictEqual(completeCache(cache,job,now),false,'critical checkpoint invalidates otherwise fresh eight-hour cache');
assert.strictEqual(completeCache({...cache,updatedAt:'2026-10-08T22:50:00Z'},job,now),true,'recent refresh avoids duplicate calls');
assert.strictEqual(completeCache({...cache,updatedAt:'2026-10-08T23:01:00Z'},job,now),true,'checkpoint satisfied');
assert.strictEqual(nextJob([{job:'old-defense',store:'weekly-sage-defense',ready:false},{...job,ready:false}],now).store,'player-data','critical availability is independent of historical backfill');
let ledger=null,version=0;
const budgetStore={getWithMetadata:async()=>ledger?{data:structuredClone(ledger),etag:String(version)}:null,setJSON:async(_k,v,o)=>{if((o.onlyIfNew&&ledger)||(o.onlyIfMatch&&o.onlyIfMatch!==String(version)))return{modified:false};ledger=v;version++;return{modified:true};}};
(async()=>{
 const getStore=({name})=>({get:async()=>name==='weekly-sage-schedule'?schedule:name==='player-data'?cache:null});
 const rows=await inspectJobs(getStore,2026,5,now);assert.strictEqual(rows.find(r=>r.store==='player-data').ready,false);
 const options={job:'refresh-player-data',calls:33,priority:'injury',maxJobCalls:132};
 const results=await Promise.all(Array.from({length:8},()=>reserveTank01Calls({},options,{store:budgetStore,now:new Date(now),limit:700,normalLimit:600})));
 assert.strictEqual(results.filter(r=>r.allowed).length,4);assert.strictEqual(ledger.reserved,132,'all triggers share atomic per-job cap');
 assert.ok(results.some(r=>r.reason==='job-daily-limit'));
 assert.strictEqual((await reserveTank01Calls({},{job:'normal',calls:569},{store:budgetStore,now:new Date(now),limit:700,normalLimit:600})).allowed,false,'global cap still applies');
 console.log('Critical availability: practice, kickoff windows, DST, international games, no post-kickoff refresh, recent-cache dedup and concurrent per-job/global caps. No provider calls.');
})().catch(e=>{console.error(e);process.exitCode=1;});
