const {
  runDecisionEngine,
  scorePlayer,
  applyHardRules,
  classifyAction,
  selectRecommendationSet,
  buildRationale,
  computeValueRoleScore,
  deriveSageAction,
  buildSageExplanation,
  buildRecommendationEntry,
  THRESHOLD_TARGET,
  THRESHOLD_WATCH,
  MORE_TARGETS_COUNT,
  SAGE_ACTION_TAKE_NOW,
  SAGE_ACTION_CONSIDER_NOW,
  SAGE_ACTION_FLEXIBLE,
  SAGE_ACTION_CAUTION,
  SAGE_ACTION_NEEDS_MORE_EVIDENCE,
  SAGE_ACTION_LABELS
} = require('../decision-engine.js');

let passed = 0;
let failed = 0;
const failures = [];

function check(name, condition) {
  if (condition) {
    passed++;
  } else {
    failed++;
    failures.push(name);
  }
}

// ─── Helpers ────────────────────────────────────────────────

function diag(overrides) {
  return Object.assign(
    {
      player: 'Test Player',
      pos: 'RB',
      maxPrice: 40,
      finalScore: 0.5,
      action: 'WATCH',
      valueScore: 0.5,
      needScore: 0.5,
      inflationScore: 0.5,
      strategyScore: 0.5,
      budgetScore: 0.5,
      reasonCodes: [],
      riskCodes: [],
      positionalInflationFallback: true
    },
    overrides
  );
}

function makeState(overrides) {
  return Object.assign(
    {
      userTeam: 'Me',
      teamNames: ['Me', 'Rival'],
      budget: 200,
      numTeams: 2,
      roster: { QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, K: 1, DEF: 1, BENCH: 6 },
      strategy: null,
      scoring: 'ppr',
      draftLog: [],
      playerPriceLookup: {},
      defRankLookup: {}
    },
    overrides
  );
}

function makePlayer(name, pos, targetPrice) {
  return { name: name, pos: pos, targetPrice: targetPrice };
}

// ═══════════════════════════════════════════════════════════
// UNCHANGED-BEHAVIOR PROOF -- the existing, validated engine must
// produce byte-for-byte identical decisions with SAGE fields present.
// ═══════════════════════════════════════════════════════════

(function () {
  var allPlayers = [
    makePlayer('Alpha RB', 'RB', 30),
    makePlayer('Bravo WR', 'WR', 25),
    makePlayer('Charlie RB', 'RB', 18),
    makePlayer('Delta TE', 'TE', 12),
    makePlayer('Echo QB', 'QB', 20)
  ];
  var priceLookup = {};
  allPlayers.forEach(function (p) { priceLookup[p.name.toLowerCase()] = p.targetPrice; });
  var state = makeState({ playerPriceLookup: priceLookup });
  var result = runDecisionEngine(state, allPlayers);

  check('target ordering unchanged: recommendations sorted by finalScore desc', (function () {
    var scores = result.recommendations.map(function (r) { return r.finalScore; });
    for (var i = 1; i < scores.length; i++) {
      if (scores[i] > scores[i - 1]) return false;
    }
    return true;
  })());

  check('PRIMARY role assigned to the top-scored viable candidate', result.recommendations[0] && result.recommendations[0].role === 'PRIMARY');
  check('ALTERNATIVE role present as the second entry', result.recommendations[1] && result.recommendations[1].role === 'ALTERNATIVE');
  check('VALUE role present as the third entry', result.recommendations[2] && result.recommendations[2].role === 'VALUE');
  check('MORE targets role is MORE', !result.moreTargets.length || result.moreTargets[0].role === 'MORE');

  check('Decision Score is Math.round(finalScore*100), unchanged formula', result.recommendations.every(function (r) {
    return r.decisionScore === Math.round(r.finalScore * 100);
  }));

  check('Max Bid (maxPrice) present and a positive number on every recommendation', result.recommendations.every(function (r) {
    return typeof r.maxPrice === 'number' && r.maxPrice > 0;
  }));

  check('action (TARGET/WATCH/PASS) present on every recommendation, from the unmodified classifyAction()', result.recommendations.every(function (r) {
    return ['TARGET', 'WATCH', 'PASS'].indexOf(r.action) !== -1;
  }));

  check('rationale field still present and generated by the original buildRationale() (untouched)', result.recommendations.every(function (r) {
    return typeof r.rationale === 'string' && r.rationale.length > 0;
  }));
})();

(function () {
  // Budget/roster-full hard-rule behavior unchanged.
  var state = makeState({
    userTeam: 'Me',
    roster: { QB: 1, RB: 0, WR: 0, TE: 0, FLEX: 0, K: 0, DEF: 0, BENCH: 0 },
    draftLog: [{ player: 'Someone', pos: 'QB', team: 'Me', price: 10 }]
  });
  var result = runDecisionEngine(state, [makePlayer('X', 'RB', 10)]);
  check('ROSTER_FULL status unchanged when totalOpenSlots is 0', result.status === 'ROSTER_FULL');
})();

(function () {
  check('classifyAction threshold behavior unchanged: exactly at THRESHOLD_TARGET is TARGET', classifyAction(THRESHOLD_TARGET) === 'TARGET');
  check('classifyAction threshold behavior unchanged: just under THRESHOLD_TARGET is WATCH (if >= THRESHOLD_WATCH)', classifyAction(THRESHOLD_TARGET - 0.001) === 'WATCH');
  check('classifyAction threshold behavior unchanged: exactly at THRESHOLD_WATCH is WATCH', classifyAction(THRESHOLD_WATCH) === 'WATCH');
  check('classifyAction threshold behavior unchanged: just under THRESHOLD_WATCH is PASS', classifyAction(THRESHOLD_WATCH - 0.001) === 'PASS');
})();

// ═══════════════════════════════════════════════════════════
// AUCTION SAGE -- deriveSageAction()
// ═══════════════════════════════════════════════════════════

check('TARGET + no risk evidence -> TAKE_NOW', deriveSageAction(diag({ action: 'TARGET', riskCodes: [] })) === SAGE_ACTION_TAKE_NOW);
check('TARGET + risk evidence -> CONSIDER_NOW (moderated, not downgraded to a lower internal tier)', deriveSageAction(diag({ action: 'TARGET', riskCodes: ['BUDGET_TIGHT_AFTER_PICK'] })) === SAGE_ACTION_CONSIDER_NOW);
check('WATCH + no risk evidence -> FLEXIBLE', deriveSageAction(diag({ action: 'WATCH', riskCodes: [] })) === SAGE_ACTION_FLEXIBLE);
check('WATCH + risk evidence -> CAUTION', deriveSageAction(diag({ action: 'WATCH', riskCodes: ['RB_DEPTH_THIN'] })) === SAGE_ACTION_CAUTION);
check('PASS + some positive evidence -> CAUTION (a real, if weak, case exists)', deriveSageAction(diag({ action: 'PASS', reasonCodes: ['target value'], riskCodes: [] })) === SAGE_ACTION_CAUTION);
check('PASS + zero evidence either way -> NEEDS_MORE_EVIDENCE only in this genuinely-empty case', deriveSageAction(diag({ action: 'PASS', reasonCodes: [], riskCodes: [] })) === SAGE_ACTION_NEEDS_MORE_EVIDENCE);

check('deriveSageAction never invents a new classification -- always one of the 5 named constants', ['TARGET', 'WATCH', 'PASS'].every(function (action) {
  return [SAGE_ACTION_TAKE_NOW, SAGE_ACTION_CONSIDER_NOW, SAGE_ACTION_FLEXIBLE, SAGE_ACTION_CAUTION, SAGE_ACTION_NEEDS_MORE_EVIDENCE]
    .indexOf(deriveSageAction(diag({ action: action, riskCodes: [], reasonCodes: [] }))) !== -1;
}));

check('deriveSageAction reads diag.action directly -- never recomputes finalScore or a new threshold', (function () {
  var d = diag({ action: 'TARGET', finalScore: 0.999999, riskCodes: [] });
  var a1 = deriveSageAction(d);
  d.finalScore = 0.0001; // tampering with finalScore alone must not change the outcome
  var a2 = deriveSageAction(d);
  return a1 === a2;
})());

// ═══════════════════════════════════════════════════════════
// AUCTION SAGE -- buildSageExplanation()
// ═══════════════════════════════════════════════════════════

(function () {
  var d = diag({ action: 'TARGET', pos: 'RB', needScore: 1.0, valueScore: 0.8, maxPrice: 53, reasonCodes: ['RB need', 'target value'], riskCodes: [] });
  var action = deriveSageAction(d);
  var text = buildSageExplanation(action, d, {});
  check('TARGET + strong positive evidence: explanation mentions the actual need signal', text.indexOf('starting need') !== -1);
  check('TARGET + strong positive evidence: explanation mentions the actual value signal', text.indexOf('strong') !== -1);
  check('TARGET + strong positive evidence: Max Bid appears as the ceiling', text.indexOf('$53') !== -1);
  check('TAKE_NOW explanation frames Max Bid as a "do not chase past" boundary', text.toLowerCase().indexOf("don't chase") !== -1 || text.toLowerCase().indexOf('do not chase') !== -1);
})();

(function () {
  var d = diag({ action: 'TARGET', needScore: 1.0, valueScore: 0.75, budgetScore: 0.15, maxPrice: 30, reasonCodes: ['RB need'], riskCodes: ['BUDGET_TIGHT_AFTER_PICK'] });
  var action = deriveSageAction(d);
  var text = buildSageExplanation(action, d, {});
  check('TARGET + meaningful risk: explanation references the actual budget risk', text.indexOf('budget tight') !== -1);
  check('TARGET + meaningful risk: Max Bid still present', text.indexOf('$30') !== -1);
  check('CONSIDER_NOW wording is moderated, not identical to TAKE_NOW wording', text.toLowerCase().indexOf('carefully') !== -1);
})();

(function () {
  var d = diag({ action: 'WATCH', needScore: 0.3, maxPrice: 15, reasonCodes: [], riskCodes: [] });
  var action = deriveSageAction(d);
  var text = buildSageExplanation(action, d, {});
  check('WATCH + no risk: FLEXIBLE framing does not force urgency', text.toLowerCase().indexOf('no need to force it') !== -1);
})();

(function () {
  var d = diag({ action: 'WATCH', pos: 'TE', needScore: 1.0, valueScore: 0.2, maxPrice: 22, riskCodes: ['TE_DEPTH_THIN'], reasonCodes: [] });
  var action = deriveSageAction(d);
  var text = buildSageExplanation(action, d, {});
  check('meaningful risk (thin depth): explanation references the actual depth risk', text.indexOf('thin') !== -1);
  check('CAUTION wording reflects a weakened case, not an aggressive one', text.toLowerCase().indexOf("don't chase") === -1);
})();

(function () {
  var d = diag({ action: 'PASS', needScore: 0.0, valueScore: 0.4, maxPrice: 8, reasonCodes: [], riskCodes: [] });
  var action = deriveSageAction(d);
  check('insufficient evidence maps to NEEDS_MORE_EVIDENCE only in this genuinely-empty-evidence case', action === SAGE_ACTION_NEEDS_MORE_EVIDENCE);
})();

(function () {
  // Conflicting evidence (thin depth pushing urgency, weak value pushing
  // against it) must be RECONCILED into one coherent statement, not
  // presented as two contradictory bullets.
  var d = diag({ action: 'WATCH', pos: 'TE', needScore: 1.0, valueScore: 0.2, maxPrice: 22, riskCodes: ['TE_DEPTH_THIN'], reasonCodes: [] });
  var action = deriveSageAction(d);
  var text = buildSageExplanation(action, d, {});
  check('conflicting evidence (thin depth + weak value) reconciled into a single connected clause', text.indexOf('but the price/value trade-off') !== -1);
  // Must NOT contain both an unqualified "strong value" claim and a
  // separate weak-value claim in the same explanation.
  check('no contradictory separate "value is strong" claim when value is actually weak', text.indexOf('value at this price is strong') === -1);
})();

(function () {
  // Two candidates with IDENTICAL evidence must produce IDENTICAL text --
  // no artificial linguistic variety.
  var d1 = diag({ action: 'TARGET', pos: 'WR', needScore: 1.0, valueScore: 0.8, maxPrice: 40, reasonCodes: ['WR need'], riskCodes: [] });
  var d2 = diag({ action: 'TARGET', pos: 'WR', needScore: 1.0, valueScore: 0.8, maxPrice: 40, reasonCodes: ['WR need'], riskCodes: [], player: 'A Different Player' });
  var t1 = buildSageExplanation(deriveSageAction(d1), d1, {});
  var t2 = buildSageExplanation(deriveSageAction(d2), d2, {});
  check('identical evidence produces identical explanation text (no fabricated variety)', t1 === t2);
})();

// ═══════════════════════════════════════════════════════════
// buildRecommendationEntry() -- additive fields only
// ═══════════════════════════════════════════════════════════

(function () {
  var d = diag({ action: 'TARGET', player: 'Sample Player', pos: 'WR', needScore: 1.0, valueScore: 0.8, maxPrice: 44, finalScore: 0.75, reasonCodes: ['WR need'], riskCodes: [] });
  var entry = buildRecommendationEntry('PRIMARY', d, { scoringFormat: 'ppr' }, []);

  check('existing fields on the entry are untouched', entry.role === 'PRIMARY' && entry.player === 'Sample Player' && entry.pos === 'WR' && entry.maxPrice === 44 && entry.decisionScore === 75 && entry.action === 'TARGET');
  check('rationale (original role-based text) is still present and unchanged in shape', typeof entry.rationale === 'string');
  check('new sageAction field present', entry.sageAction === SAGE_ACTION_TAKE_NOW);
  check('new sageActionLabel field present and human-readable', entry.sageActionLabel === SAGE_ACTION_LABELS.TAKE_NOW);
  check('new sageExplanation field present and non-empty', typeof entry.sageExplanation === 'string' && entry.sageExplanation.length > 0);
  check('role label (PRIMARY) and SAGE action (TAKE_NOW) are separate fields, not merged into one', entry.role !== entry.sageAction);
})();

console.log('decision-engine.test.js: ' + passed + '/' + (passed + failed) + ' passed');
if (failures.length) {
  failures.forEach(function (f) { console.error('FAIL:', f); });
  process.exit(1);
}
