'use strict';
const assert=require('node:assert/strict');
const {validateClaims}=require('../netlify/functions/_super-sage-rookie-claim-checks');
const {validateBackfieldCoverage}=require('../netlify/functions/_super-sage-rookie-backfield-checks');
const {focusEvidence}=require('../netlify/functions/_super-sage-shadow-fast-review');
const role={name:'Will Shipley',position:'RB',facts:[{field:'stateChanges',factId:'B:stateChanges',value:[{type:'ROLE_CHANGE',verified:true}]},{field:'backfieldContext',factId:'B:backfieldContext',value:{roleOrderVerified:true,reportedRoles:{candidateListedRank:3,players:[{name:'Saquon Barkley',listedRank:1,status:'OUT'},{name:'Tank Bigsby',listedRank:2,status:'IR'},{name:'Will Shipley',listedRank:3,status:'UNKNOWN'}],notListedInChart:['Dameon Pierce','Jaydon Blue']}}},{field:'roleExpansion',factId:'B:roleExpansion',value:{validated:false}}]};
const packet={players:[role]};
const forecast={explanation:'I expect Shipley is in line for more work because Barkley is OUT and Bigsby is on IR, but the amount is unknown.'};
assert(!validateClaims(forecast,packet).includes('unverified_workload_increase'));
assert(validateClaims({explanation:'Shipley is in line for more work.'},packet).includes('unverified_workload_increase'));
assert(validateClaims(forecast,{players:[{...role,facts:role.facts.filter(f=>f.field!=='stateChanges')}]}).includes('unverified_workload_increase'),'forecast needs supplied change evidence');
assert(validateClaims({explanation:'Shipley will get 18 touches.'},packet).includes('guaranteed_future_workload'));
assert(validateClaims({explanation:'I expect Shipley to get 18 touches.'},packet).includes('unsupported_numeric_workload_forecast'));
const corum={name:'Blake Corum',position:'RB',facts:[{field:'backfieldContext',value:{roleOrderVerified:false,candidateSourceOrder:2}},{field:'observedOpportunity',value:{lastGame:7,avgLast3:10}}]};
assert(validateClaims({explanation:'Corum sits second in the Rams backfield.'},{players:[corum]}).includes('unverified_backfield_role_order'));
assert(!validateClaims({explanation:'Corum has an unverified backfield role order.'},{players:[corum]}).includes('unverified_backfield_role_order'));
const coverage={factIds:['B:backfieldContext','B:roleExpansion'],explanation:"Shipley faces a tough matchup; Pierce and Blue have unknown status and are not listed on the chart. Barkley is OUT and Bigsby is on IR. We don't know how much workload Shipley receives."};
assert(validateBackfieldCoverage(coverage,packet).includes('missing_candidate_health_uncertainty'),'other backs unknown status does not satisfy Shipley health coverage');
assert(!validateBackfieldCoverage({...coverage,explanation:coverage.explanation+' Shipley has UNKNOWN chart status despite an ACTIVE listing.'},packet).includes('missing_candidate_health_uncertainty'));
const frozen={packet:{players:[corum,role],request:{}}};const before=JSON.stringify(frozen);
const pair=focusEvidence(frozen,['Blake Corum','Will Shipley']);assert(pair.packet.players[0].facts.some(f=>f.field==='observedOpportunity'));assert.equal(JSON.stringify(frozen),before);
console.log('PASS supported qualitative forecast; unsupported certainty, invented count/order and misplaced health coverage rejected; observed baseline included; frozen input unchanged. No provider calls.');
