'use strict';
const assert=require('node:assert/strict');
const {backfieldEvidence}=require('../netlify/functions/_backfield-evidence');
const {buildLineupDecisionRecord}=require('../netlify/functions/_super-sage-lineup-decision');
const {buildEvidence}=require('../netlify/functions/_super-sage-shadow-llm');
const {focusEvidence}=require('../netlify/functions/_super-sage-shadow-fast-review');
const now=new Date('2026-10-09T02:30:00Z');
// Synthetic depth/status evidence; this fixture is not a live status assertion.
const row={name:'Saquon Barkley',position:'RB',team:'PHI',playerID:'1',rank:8,recommendation:'START'};
const cache={source:'Tank01',generatedAt:'2026-10-09T00:00:00Z',teams:{PHI:{RB:[{longName:row.name,playerID:'1',depth:1},{longName:'Will Shipley',playerID:'2',depth:2},{longName:'Tank Bigsby',playerID:'3',depth:3}]}}};
const availability={fresh:true,updatedAt:'2026-10-09T00:01:00Z',players:{'1':{longName:row.name,team:'PHI',pos:'RB',injury:{designation:'QUESTIONABLE'}},'2':{longName:'Will Shipley',team:'PHI',pos:'RB'},'3':{longName:'Tank Bigsby',team:'PHI',pos:'RB',injury:{designation:'IR'}}},transactions:[]};
const evidence=backfieldEvidence(row,cache,availability,2026,5,now);
assert.equal(evidence.candidateDepth,1);assert.equal(evidence.players[1].name,'Will Shipley');assert.equal(evidence.players[1].depth,2);
assert.equal(evidence.players[1].availability.status,'UNKNOWN','missing injury is not active/healthy clearance');
assert.equal(evidence.players[2].availability.status,'IR');assert.equal(evidence.redistributionVerified,false);
assert.equal(evidence.players[2].availability.reportedAt,availability.updatedAt);
for(const changed of [{...cache,generatedAt:'2026-10-07T00:00:00Z'},{...cache,generatedAt:'2026-10-10T00:00:00Z'},{...cache,source:'unverified'},null]) assert.equal(backfieldEvidence(row,changed,availability,2026,5,now),null);
assert.equal(backfieldEvidence(row,cache,availability,2026,4,now),null,'no current depth in historical week');
assert.equal(backfieldEvidence({...row,team:'LAR'},cache,availability,2026,5,now),null);
assert.equal(backfieldEvidence({...row,playerID:'wrong'},cache,availability,2026,5,now),null);
const duplicate=structuredClone(cache);duplicate.teams.PHI.RB.push({...duplicate.teams.PHI.RB[1],depth:4});assert.equal(backfieldEvidence(row,duplicate,availability,2026,5,now),null);
const stale=backfieldEvidence(row,cache,{...availability,updatedAt:'2026-10-08T00:00:00Z'},2026,5,now);assert(stale.players.every(p=>p.availability.status==='UNKNOWN'));
const tx=backfieldEvidence(row,cache,{...availability,transactions:[{name:'Tank Bigsby',team:'PHI',position:'RB',season:2026,fromWeek:5,status:'ACTIVE',source:'official',reportedAt:'2026-10-08'}]},2026,5,now);assert.equal(tx.players[2].availability.status,'ACTIVE','later authoritative activation supersedes cached IR');
const stillHurt=backfieldEvidence(row,cache,{...availability,transactions:[{name:row.name,team:"PHI",position:"RB",season:2026,fromWeek:5,status:"ACTIVE",source:"official",reportedAt:"2026-10-08"}]},2026,5,now);assert.equal(stillHurt.players[0].availability.status,"QUESTIONABLE","activation is not injury clearance");
const other={name:'Blake Corum',position:'RB',team:'LAR',rank:9,recommendation:'START'};
const args={rankings:{positions:{RB:[row,other]}},roster:[row,other],slots:[{slotLabel:'RB',eligiblePositions:['RB'],count:1}],scoring:'half',season:2026,week:5};
const old=buildEvidence(buildLineupDecisionRecord(args)),snapshot=JSON.stringify(old);
row.backfieldContext=evidence;
const record=buildLineupDecisionRecord(args);assert.deepEqual(record.slots[0].starter.backfieldContext,evidence);
const frozen=buildEvidence(record);const focused=focusEvidence(frozen,[row.name,other.name]);
assert.deepEqual(focused.packet.players[0].facts.find(f=>f.field==='backfieldContext').value,evidence);
assert.equal(JSON.stringify(old),snapshot,'previous frozen packets remain unchanged');assert.notEqual(frozen.evidenceHash,old.evidenceHash);
console.log('PASS: cached depth provenance, identity, freshness, unknown health, activation, persisted decision and frozen/focused evidence; no provider calls.');
