'use strict';
const assert = require('assert');
const {buildAutomaticShadowRecord,shadowSlot,evidenceFacts} = require('../netlify/functions/_super-sage-live-shadow-adapter');
const {inferFact} = require('../netlify/functions/_super-sage-operator-unscripted');
const {buildLiveShadowComparison} = require('../netlify/functions/_super-sage-live-shadow');
const production = require('./fixtures/super-sage-live-shadow-week5.json');
const before = JSON.stringify(production);
const shadow = buildAutomaticShadowRecord(production);
const comparison = buildLiveShadowComparison({season:2026,week:5,scoring:'half',productionRecord:production,shadowRecord:shadow});
assert.strictEqual(JSON.stringify(production),before,'frozen production must not mutate');
assert.strictEqual(shadow.slots.length,10);
assert.strictEqual(comparison.slots.length,10,'RB, WR and FLEX occurrences must not collapse');
assert.strictEqual(new Set(comparison.slots.map(s=>s.slotKey)).size,10);
assert.strictEqual(comparison.summary.noCalls,9,'four no-comparator and five unresolved injury/environment/role cases');
assert.strictEqual(comparison.summary.agreements,1,'no-comparator passthroughs cannot masquerade as independent agreements');
for (const name of ['Saquon Barkley','Malik Nabers','Terry McLaurin']) {
 const i=production.slots.findIndex(s=>s.starter.name===name);
 const s=shadow.slots[i];
 assert.strictEqual(s.starter,null,name+' must not get a definitive shadow start from unresolved evidence');
 assert.strictEqual(s.shadow.callStatus,'CONDITIONAL');
 assert.strictEqual(s.shadow.informationState,'OPEN');
 assert.strictEqual(s.confidence.label,'LOW');
 assert.ok(s.shadow.missingInformation.length);
 assert.ok(!s.explanation,'do not inherit Production explanation as Rookie voice');
}
const corum=shadow.slots.find(s=>s.shadow?.incumbent==='Blake Corum');
const projection=corum.shadow.evidenceUsed.find(e=>e.group==='projection');
assert.strictEqual(projection.effect,'CHALLENGES_PRIOR','Sutton projection advantage must challenge Corum');
assert.ok(projection.text.includes('Courtland Sutton'));
assert.strictEqual(corum.shadow.uncertaintyType,'CLOSE_CALL');
const bare={slotLabel:'WR',starter:{name:'A'},comparator:{name:'B'},confidence:{label:'Moderate'}};
const empty=shadowSlot(bare);
assert.strictEqual(empty.starter,null);
assert.strictEqual(empty.shadow.callStatus,'NO_CALL');
assert.strictEqual(empty.confidence.label,'LOW');
const pair=(a,b)=>evidenceFacts({name:'A',matchup:a},{name:'B',matchup:b}).map(inferFact);
assert.strictEqual(pair('Positive','Negative')[0].effect,'REINFORCES_PRIOR');
assert.strictEqual(pair('Negative','Positive')[0].effect,'CHALLENGES_PRIOR');
assert.strictEqual(pair('Neutral','Neutral').length,0);
assert.strictEqual(pair('Unknown','Positive').length,0,'unknown matchup cannot be invented');
assert.strictEqual(pair({label:'Negative'},{label:'Positive'})[0].effect,'CHALLENGES_PRIOR');
assert.strictEqual(inferFact({text:'projection edge',verified:false,effect:'REINFORCES_PRIOR'}).effect,'CONFLICTED_UNKNOWN','unverified typed fact still rejected');
const change={type:'ROLE_CHANGE',verified:true,magnitudeValidated:false,note:'Teammate absent; redistribution unknown.'};
const facts=evidenceFacts({name:'A',stateChanges:[]},{name:'B',stateChanges:[change]});
assert.strictEqual(inferFact(facts[0]).effect,'REASSESS_PRIOR','unknown redistribution is reassessment, never an invented benefit');
const limited=shadowSlot({slotLabel:'RB',starter:{name:'A',position:'RB',standing:{tier:'START',positionRank:1}},comparator:{name:'B',position:'RB',standing:{tier:'START',positionRank:2}},confidence:{label:'Limited'}});
assert.strictEqual(limited.confidence.label,'LOW','do not raise Production Limited to Moderate');
const unavailable=shadowSlot({...bare,starter:{name:'A',availability:{unavailable:true},projection:{admissible:true,points:20}},comparator:{name:'B',projection:{admissible:true,points:10}}});
assert.strictEqual(unavailable.starter,null);
assert.strictEqual(unavailable.shadow.callStatus,'NO_CALL');
assert.ok(shadow.slots.every(s=>s.hasValidatedEdge===false));
console.log('Frozen live Week 5 Rookie evidence direction, uncertainty and ten-slot comparison: PASS');
