"use strict";
const assert=require("assert");
const fs=require("fs");
const path=require("path");
const p=path.join(__dirname,"../netlify/functions/_super-sage-lineup-service.js");
const src=fs.readFileSync(p,"utf8");
assert.ok(src.includes('require("./_super-sage-live-shadow.js")'),"shared service must import shadow harness");
assert.ok(src.includes("shadowRecord = null"),"explicit shadow override must remain optional");
assert.ok(src.includes('require("./_super-sage-live-shadow-adapter.js")'),"shared service must import automatic Rookie adapter");
assert.ok(src.includes("const record = buildLineupDecisionRecord"),"production decision must still be built by frozen authority");
const prodAt=src.indexOf("const record = buildLineupDecisionRecord");
const adapterAt=src.indexOf("const automaticShadowRecord = shadowRecord || buildAutomaticShadowRecord(record)");
const shadowAt=src.indexOf("const shadowComparison = buildLiveShadowComparison");
assert.ok(prodAt>=0&&adapterAt>prodAt&&shadowAt>adapterAt,"production record must be created before automatic Rookie and comparison");
assert.ok(src.includes("productionRecord: record"),"shadow comparison must observe the production record");
assert.ok(src.includes("shadowRecord: automaticShadowRecord"),"comparison must use the isolated Rookie record");
assert.ok(src.includes("shadowComparison\n  };")||src.includes("shadowComparison\r\n  };"),"service may return observational artifact");
assert.ok(!src.includes("record = shadowRecord"),"shadow must never replace production record");
assert.ok(!src.includes("buildLineupDecisionRecord(shadow"),"shadow must never enter production authority");
console.log("Shared lineup shadow attachment boundary: PASS");
