'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {SOURCES,parseRoles,reportedRoles,collectRoles}=require('../netlify/functions/_team-backfield-roles');
const {buildEvidence}=require('../netlify/functions/_super-sage-shadow-llm');
const {focusEvidence}=require('../netlify/functions/_super-sage-shadow-fast-review');
const html=fs.readFileSync(__dirname+'/fixtures/team-depth/phi-offense-20261008.html','utf8'),now=new Date('2026-10-09T03:00:00Z');
const report=parseRoles(html,SOURCES[0],now.toISOString());
assert.deepEqual(report.players.map(p=>[p.name,p.listedRank]),[['Saquon Barkley',1],['Tank Bigsby',2],['Will Shipley',3]]);
assert.equal(report.publishedAt,null,'observation time is not invented publication time');assert.equal(report.chartType,'TEAM_PUBLISHED_UNOFFICIAL');
assert.throws(()=>parseRoles('<html>Login</html>',SOURCES[0],now.toISOString()),/contract/);
assert.throws(()=>parseRoles(html.replace('>First<','>Order<'),SOURCES[0],now.toISOString()),/order contract/);
assert.throws(()=>parseRoles(html.replace('>Will Shipley<','>Tank Bigsby<'),SOURCES[0],now.toISOString()),/Incomplete/);
const row={name:'Saquon Barkley',position:'RB',team:'PHI'};
const context={generatedAt:now.toISOString(),roleOrderVerified:false,players:[{name:'Will Shipley',sourceOrder:1,availability:{status:'UNKNOWN'}},{name:row.name,sourceOrder:2,availability:{status:'QUESTIONABLE'}},{name:'Tank Bigsby',sourceOrder:5,availability:{status:'IR'}},{name:'Dameon Pierce',sourceOrder:3,availability:{status:'UNKNOWN'}}]};
const before=JSON.stringify(context),enriched=reportedRoles(context,row,{teams:{PHI:report}},now);
assert.equal(enriched.reportedRoles.candidateListedRank,1);assert.equal(enriched.reportedRoles.nextListedAlternative.name,'Will Shipley');assert.equal(enriched.reportedRoles.nextListedAlternative.status,'UNKNOWN');
assert.deepEqual(enriched.reportedRoles.notListedInChart,['Dameon Pierce']);assert.equal(JSON.stringify(context),before);
assert.strictEqual(reportedRoles(context,row,{teams:{PHI:{...report,observedAt:'2026-10-07T00:00:00Z'}}},now),context);
assert.strictEqual(reportedRoles(context,row,{teams:{PHI:{...report,sourceUrl:'https://untrusted.example'}}},now),context);
for(const bad of [{...report,team:"LAR"},{...report,observedAt:"2026-10-10T00:00:00Z"},{...report,players:[report.players[0],report.players[0]]}])assert.strictEqual(reportedRoles(context,row,{teams:{PHI:bad}},now),context);
const available=structuredClone(context);available.players[2].availability.status='ACTIVE';assert.equal(reportedRoles(available,row,{teams:{PHI:report}},now).reportedRoles.nextListedAlternative.name,'Tank Bigsby','activation changes next listed alternative, not a hardcoded Shipley rule');
const candidate={...row,backfieldContext:enriched},other={name:'Blake Corum',position:'RB'};
const frozen=buildEvidence({decisionId:'a'.repeat(64),request:{season:2026,week:5},slots:[{slotLabel:'RB',eligiblePositions:['RB'],starter:candidate,comparator:other}]});
assert.equal(focusEvidence(frozen,[row.name,other.name]).packet.players[0].facts.find(f=>f.field==='backfieldContext').value.reportedRoles.nextListedAlternative.name,'Will Shipley');
(async()=>{
 const records=new Map();let sequence=0,calls=0;
 const store={get:async k=>records.get(k)?.data||null,getWithMetadata:async k=>records.get(k)||null,setJSON:async(k,data,o={})=>{const old=records.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return{modified:false};records.set(k,{data:structuredClone(data),etag:String(++sequence)});return{modified:true};}};
 const fetcher=async(url)=>{calls++;assert.equal(url,SOURCES[0].url);return{ok:true,text:async()=>html};};
 await Promise.all(Array.from({length:4},()=>collectRoles({store,fetcher,now})));assert.equal(calls,1,'atomic dedup');
 await collectRoles({store,fetcher,now:new Date(+now+3600000)});assert.equal(calls,1,'six-hour successful collection cadence');
 const previous=JSON.stringify(await store.get('latest'));const failed=await collectRoles({store,fetcher:async()=>({ok:true,text:async()=>'<html>Login</html>'}),now:new Date(+now+7*3600000)});
 assert.equal(failed.previousCachePreserved,true);assert.equal(JSON.stringify(await store.get('latest')),previous);assert((await store.get('health')).error);
 const denied=await require('../netlify/functions/refresh-team-backfield-roles').handler({httpMethod:'GET',headers:{}});assert([401,503].includes(denied.statusCode),'customer reads cannot collect sources');
 console.log('PASS: captured team chart, fail-closed parser, independent status/role evidence, alternative reassessment, immutable frozen evidence, atomic collection, six-hour dedup and failure preservation. Public source mocked; zero Tank01/LLM.');
})().catch(e=>{console.error(e);process.exitCode=1;});
