'use strict';
const assert=require('assert');
const {offensivePoints,normalizeProjectionResponse,validCache,fillProjection,matchProjection,attachProjectionPositions,scoringKey}=require('../netlify/functions/_weekly-projections');
const now=new Date('2026-09-30T05:00:00Z');
const projection=(name,pos,id)=>({longName:name,pos,team:'SEA',playerID:id,Passing:{passYds:'250',passTD:'2',int:'1'},Rushing:{rushYds:'20',rushTD:'0'},Receiving:{recYds:'10',recTD:'0',receptions:'2'},fumblesLost:'0',twoPointConversion:'0',fantasyPointsDefault:{standard:'19',halfPPR:'20',PPR:'21'}});
const payload={body:{playerProjections:{},teamDefenseProjections:{SEA:{teamAbv:'SEA',fantasyPointsDefault:'7.2'}}}};
for(const pos of ['QB','RB','WR','TE','K']) for(let i=0;i<24;i++)payload.body.playerProjections[pos+i]=projection('Player '+pos+' '+i,pos,pos+i);
const cache=normalizeProjectionResponse(payload,2026,4,now);
assert.equal(cache.rows.length,121);assert.equal(cache.counts.DEF,1);
assert.deepEqual(offensivePoints(projection('QB','QB','1')),{standard:19,half:20,ppr:21});
assert.equal(offensivePoints({...projection('QB','QB','1'),Receiving:{}}),null,'missing projected stats cannot become zero');
assert.equal(scoringKey('half-PPR'),'half');assert.equal(scoringKey('mystery'),null);
assert(validCache(cache,2026,4,24*3600000,now.getTime()));
assert(!validCache(cache,2026,5,24*3600000,now.getTime()));
assert(!validCache(cache,2026,4,24*3600000,now.getTime()+25*3600000));
const half={...cache,scoring:'half',fresh:true,rows:cache.rows.map(row=>({...row,projectedPoints:row.points.half}))};
const candidate={name:'Player RB 1',position:'RB',nflTeam:'SEA',projectedPoints:null};
const filled=fillProjection(candidate,half);assert.equal(filled.projectedPoints,20);assert.equal(filled.projection.source,'Tank01');assert.equal(filled.projection.week,4);
assert.equal(fillProjection({...candidate,projectedPoints:12.3},half).projectedPoints,12.3,'retain an actual league-provider projection');
assert.equal(fillProjection({...candidate,projectedPoints:99},half,true).projectedPoints,20,'stale league projections must use current cache');
assert.equal(fillProjection({...candidate,projectedPoints:99},null,true).projectedPoints,null,'stale numbers must not survive a current-cache outage');
assert.equal(matchProjection({...candidate,nflTeam:'BUF'},half),null,'wrong team must fail closed');
assert.equal(matchProjection({...candidate,position:'WR'},half),null,'wrong position must fail closed');
const duplicate={...half,rows:[...half.rows,{...half.rows.find(row=>row.name===candidate.name)}]};
assert.equal(matchProjection(candidate,duplicate),null,'ambiguous identities must fail closed');
assert.equal(fillProjection({name:'Seattle Seahawks',position:'DEF',nflTeam:'SEA'},half).projectedPoints,7.2);
const positions={RB:[{...candidate,sageTake:'SAGE roster advice.'}]};const counts=attachProjectionPositions(positions,half);
assert.equal(counts.matched,1);assert(positions.RB[0].sageTake.includes('Tank01 half-PPR projection: 20.0 points.'));
assert.throws(()=>normalizeProjectionResponse({body:{playerProjections:{},teamDefenseProjections:{}}},2026,4,now),/coverage incomplete/);
assert.throws(()=>normalizeProjectionResponse({...payload,body:{...payload.body,week:3}},2026,4,now),/different season\/week/);
console.log('Projection scoring, identity joins, wrong-week rejection, freshness, and incomplete-cache protection passed.');
